# Generated by Django 5.0.2 on 2024-02-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='imageURL',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
